# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: pg
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: poc
    volumes:
      - pg:/var/lib/postgresql/data


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg:
